name: Continuous-Integration

on:
  pull_request:
    types:
      - auto_merge_enabled
    branches:
      - staging
  merge_group:

permissions:
  contents: read
  checks: read

env:
  EVENT: ${{ github.event_name }}

jobs:
  ci-tasks:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -v --cov ./src/tests/
      
      - name: Install dependencies for Test PyPI
        run: |
          echo "📦 Installing Python dependencies."
          python -m pip install --upgrade pip
          if [ -f requirements/staging.txt ]; then
            pip install -r requirements/staging.txt;
          fi
  
      - name: Upgrade build tools
        run: python -m pip install --upgrade build

      - name: Build the package
        run: python -m build
      
      - name: Upload to Test PyPI
        if: ${{ env.EVENT == 'merge_group' }}
        env:
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_KEY }}
        run: |
          python -m twine upload --repository testpypi dist/*

      - name: Done
        run: echo "🎉 Deployment complete!"
