---
    name: Guard Main Branch
    on:
      pull_request:
        types:
          - auto_merge_enabled
        branches:
          - main
      merge_group:
    permissions:
      contents: read
    jobs:
      branch-check:
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]') }}
        steps:
          - name: Preamble
            run: |
              echo "🎉 A ${{ github.event_name }} triggered a ${{ runner.os }} job."
              echo "🔎 The branch is ${{ github.ref_name }} in ${{ github.repository }}."
          - name: Check out repository code
            uses: actions/checkout@v7
          - name: Guard the main branch
            if: ${{ github.event_name == 'pull_request' && github.head_ref != 'staging' }}
            run: |
              echo "🚫 The main branch is protected."
              echo "🚫 Pull requests to main must come from staging branch."
              exit 1
          - name: Notify
            run: |
              echo "📣 The job has been completed."
              echo "🔔 The main branch is protected."
              echo "🍏 This job's status is ${{ job.status }}."

